FROM golang:1.23.1 AS builder 

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . . 

RUN go build -o main .

FROM ubuntu:latest  

WORKDIR /root

COPY --from=builder /app/main .
COPY .env .env  

EXPOSE 8082

CMD ["./main"]
